FROM haydnj/torch:bayes-lqo
# add support for molecule tasks 
RUN pip install rdkit
RUN pip install selfies 
RUN pip install guacamol 
RUN pip install scipy==1.10
# add support for Lunar Lander and Robot Pushing tasks 
RUN pip install multiprocess
RUN pip install swig
RUN pip install box2d box2d-kengz
RUN pip install gym 
RUN pip install box2d-py